/* global ClipboardItem */
/* global XMLSerializer */
/* global Blob */

//------------------------------------------------------------------------------

import config from '../../config/environment';

//------------------------------------------------------------------------------

const dLog = console.debug;

const trace = 0;
const SVG_NS = 'http://www.w3.org/2000/svg';
const graphSVGStylesheetURL = `${config.rootURL}assets/graph-svg.css`;

//------------------------------------------------------------------------------

/** Cache the result of graphSVGStylesheetText(), and don't repeat the request. */
let graphSVGStylesheetPromise;

//------------------------------------------------------------------------------

async function graphSVGStylesheetText() {
  if (! graphSVGStylesheetPromise) {
    graphSVGStylesheetPromise = fetch(graphSVGStylesheetURL)
      .then((response) => {
        if (! response.ok) {
          dLog('graphSVGStylesheetText', graphSVGStylesheetURL, response.status);
          return '';
        }
        return response.text();
      })
      .catch((err) => {
        console.warn('Unable to load graph SVG stylesheet: ', err);
        return '';
      });
  }

  return graphSVGStylesheetPromise;
}

function svgElementWithEmbeddedStyles(svgElement, cssText) {
  const svgClone = svgElement.cloneNode(true);

  // if ! cssText cloneNode() could perhaps be omitted.
  if (cssText) {
    const
    defs = svgClone.querySelector('defs') ||
      svgClone.insertBefore(document.createElementNS(SVG_NS, 'defs'), svgClone.firstChild),
    style = document.createElementNS(SVG_NS, 'style');

    style.setAttribute('type', 'text/css');
    style.textContent = `\n${cssText}\n`;
    defs.insertBefore(style, defs.firstChild);
  }

  return svgClone;
}


/** Use the Clipboard_API to copy an SVG element to the clipboard
 *
 * @param svgElement <svg> element handle
 * @return promise from navigator.clipboard.write().
 *
 * Generated by Gemini, via prompt : show JavaScript to use the Clipboard_API to copy an SVG element to the clipboard
 * https://share.google/aimode/WZB3WkW2ElDEUbHj1
 */
export async function copySVGToClipboard(svgElement) {
  const fnName = 'copySVGToClipboard';
  try {
    // 1. Get the SVG element and its markup
    // const svgElement = document.getElementById(svgElementId);
    const
    cssText = await graphSVGStylesheetText(),
    svgData = new XMLSerializer().serializeToString(
      svgElementWithEmbeddedStyles(svgElement, cssText)
    );
    
    // 2. Check if the browser supports 'image/svg+xml' on the clipboard
    const canCopySVG = window.ClipboardItem && 
                       ClipboardItem.supports && 
                       ClipboardItem.supports('image/svg+xml');

    if (canCopySVG) {
      // 3. Create a Blob from the SVG string
      const svgBlob = new Blob([svgData], { type: 'image/svg+xml' });
      
      // 4. Write to the clipboard as an image
      await navigator.clipboard.write([
        new ClipboardItem({
          'image/svg+xml': svgBlob
        })
      ]);
      dLog(fnName, 'SVG copied to clipboard as an image!');
    } else {
      // Fallback: Copy as plain text if SVG image format isn't supported
      await navigator.clipboard.writeText(svgData);
      dLog(fnName, 'SVG copied as plain text code.');
    }
  } catch (err) {
    console.error('Failed to copy: ', err);
  }
}
