/* global ClipboardItem */
/* global XMLSerializer */
/* global Blob */

//------------------------------------------------------------------------------

const dLog = console.debug;

const trace = 0;

//------------------------------------------------------------------------------


/** Use the Clipboard_API to copy an SVG element to the clipboard
 *
 * @param svgElement <svg> element handle
 * @return promise from navigator.clipboard.write().
 *
 * Generated by Gemini, via prompt : show JavaScript to use the Clipboard_API to copy an SVG element to the clipboard
 * https://share.google/aimode/WZB3WkW2ElDEUbHj1
 */
export async function copySVGToClipboard(svgElement) {
  const fnName = 'copySVGToClipboard';
  try {
    // 1. Get the SVG element and its markup
    // const svgElement = document.getElementById(svgElementId);
    const svgData = new XMLSerializer().serializeToString(svgElement);
    
    // 2. Check if the browser supports 'image/svg+xml' on the clipboard
    const canCopySVG = window.ClipboardItem && 
                       ClipboardItem.supports && 
                       ClipboardItem.supports('image/svg+xml');

    if (canCopySVG) {
      // 3. Create a Blob from the SVG string
      const svgBlob = new Blob([svgData], { type: 'image/svg+xml' });
      
      // 4. Write to the clipboard as an image
      await navigator.clipboard.write([
        new ClipboardItem({
          'image/svg+xml': svgBlob
        })
      ]);
      dLog(fnName, 'SVG copied to clipboard as an image!');
    } else {
      // Fallback: Copy as plain text if SVG image format isn't supported
      await navigator.clipboard.writeText(svgData);
      dLog(fnName, 'SVG copied as plain text code.');
    }
  } catch (err) {
    console.error('Failed to copy: ', err);
  }
}
