import Application from '@ember/application';
import Resolver from 'ember-resolver';
import loadInitializers from 'ember-load-initializers';
import config from 'pretzel-frontend/config/environment';

import { d3Packages } from './utils/draw/d3-initialise-global';

export default class App extends Application {
  modulePrefix = config.modulePrefix;
  podModulePrefix = config.podModulePrefix;
  Resolver = Resolver;

  //----------------------------------------------------------------------------
  // above is boilerplate generated by ember-cli-update.
  // Added for Pretzel : 
  customEvents = {
    paste: "paste"
  };
  //----------------------------------------------------------------------------

}

loadInitializers(App, config.modulePrefix);

