#-------------------------------------------------------------------------------
# Prompt
# 
# Could you create some curl API calls which create and delete some minimal datasets, blocks and features, for testing block-hooks.interceptor.ts
# 
# Here are some typical Blocks :
# ```json
# {"id":"60db12e2162b5e275164795a","scope":"1A","name":"1A","namespace":"90k","datasetId":"dataset1","featureType":"linear"},
# {"id":"60db12e2162b5e275164795b","scope":"1B","name":"1B","namespace":"90k","datasetId":"dataset1","featureType":"linear"},
# ```
# A typical Dataset :
# ```json
# {"id":"dataset1","public":false,"readOnly":true,"createdAt":"2021-06-29T12:32:34.791Z","updatedAt":"2021-06-29T12:32:34.791Z","name":"dataset1","tags":[],"type":null,"namespace":"90k","clientId":"60db102e162b5e27516170a2"}
# ```
# clientId is required, but groupId is not so I have omitted that.
# 
# some typical Features :
# ```json
# {"blockId":"60db12e2162b5e275164795a","_id":"60db12e2162b5e2751647ad6","value":[98],"name":"marker1","parentId":null,"value_0":98},
# {"blockId":"60db12e2162b5e275164795a","_id":"60db12e2162b5e2751647ae1","value":[98],"name":"marker2","parentId":null,"value_0":98}
# ```
# 
#-------------------------------------------------------------------------------
# Usage Example :
# 
# export API_PORT_EXT=3000
# source lb4app/scripts/test/block_interceptor.bash
# test_sequence_1

# Show config, either input, or modified / output.
function showConfig()
{
  echo API_HOST=$API_HOST
  echo API_PORT_EXT=$API_PORT_EXT
  echo API_PROTO=$API_PROTO
  echo API_URL_BASE=$API_URL_BASE
}

#-------------------------------------------------------------------------------

# Based on source generated by MS VSCode + GPT5.2
#

# Below is a compact curl sequence that creates a dataset, block, and feature, then deletes the block to exercise the interceptor (before‑delete cleanup + after‑save cache invalidation). It assumes you already have $Authorization and $H_json like your earlier helpers.

# I’ll use new IDs so it’s safe to run repeatedly. Replace values if you prefer.

TMP_DIR=/tmp/$USER

# Configuration
# unused=${X=y} defaults X to 'y'
unused=${API_HOST=localhost}
unused=${API_PORT_EXT=3000}
unused=${API_PROTO=http}
# e.g. http://localhost:3000/api
unused=${API_URL_BASE=$API_PROTO://$API_HOST:$API_PORT_EXT/api}
# export API_HOST API_PORT_EXT API_PROTO API_URL_BASE

# Helpers

# (local) variables are prefixed with cg_ (derived from curlGet) to reduce clashes with other environment variables.
# @param
function curlA(){ cg_method="$1"; shift; cg_endpoint="$1"; shift; cg_url="$API_URL_BASE/$cg_endpoint"; curl -s -X "$cg_method" "${H_json[@]}" -H "$Authorization" --url "$cg_url" "$@" ; }
function curlPostA(){ cg_endpoint="$1"; shift; curlA POST "$cg_endpoint" -d "$@"; }
function curlDelA(){ cg_endpoint="$1"; shift; curlA DELETE "$cg_endpoint" ; }
function curlGetA(){ cg_endpoint="$1"; shift; curlA GET "$cg_endpoint" ; }

# IDs (edit if needed)
DATASET_ID="dataset_test_hooks"
# BLOCK_ID="60db12e2162b5e2751647aa1"
# FEATURE_ID="60db12e2162b5e2751647bb1"
CLIENT_ID="60db102e162b5e27516170a2"

# 1) Create dataset
# given parameter 'name' becomes 'id'
function Create_dataset() {
curlPostA "datasets" '{
  "id": "'"$DATASET_ID"'",
  "name": "'"$DATASET_ID"'",
  "public": false,
  "readOnly": true,
  "namespace": "90k",
  "tags": [],
  "clientId": "'"$CLIENT_ID"'"
}'
}

# 2) Create block (no name -> interceptor should set from scope/namespace)
function Create_block() {
curlPostA "blocks" '{
  "name": "1A",
  "scope": "1A",
  "namespace": "90k",
  "datasetId": "'"$DATASET_ID"'",
  "featureType": "linear"
}' | tee $TMP_DIR/block.json
export BLOCK_ID=$(< $TMP_DIR/block.json jq -r .id)
}

# 3) Create feature (linked to block)
function Create_feature() {
curlPostA "features" '{
  "blockId": "'"$BLOCK_ID"'",
  "value": [98],
  "name": "marker1",
  "value_0": 98
}' | tee $TMP_DIR/feature.json
export FEATURE_ID=$(< $TMP_DIR/feature.json jq -r .id)
}
#   "parentId": null,


function test_sequence_1() {
  Create_dataset
  Create_block
  Create_feature

curlGetA "datasets/$DATASET_ID/blocks"
curlGetA "blocks/$BLOCK_ID/features"

# 4) Verify feature exists
curlGetA "features/$FEATURE_ID"

# 5) Delete block (interceptor should delete features, annotations, intervals)
# curlDelA "blocks/$BLOCK_ID"
#   OR
# 5b) Delete dataset (interceptor should delete blocks, features, annotations, intervals)
curlDelA "datasets/$DATASET_ID"

# 6) Confirm feature was deleted by hook
curlGetA "features/$FEATURE_ID"
}
# Expected outcomes:
# - Step 2: created block should have name auto‑set to scope (“1A”).
# - Step 5: deleting the block should delete related features (Step 6 should return 404).
# If you want the delete hook to also prove annotation/interval cleanup, I can add minimal annotation + interval creates to the script.
