version: "2"
# NOTE refer to the accompanying '.env' file in this folder to access
# environment variables which are passed through to docker-compose.yaml
# at run time
services:
  database: # mongo database
    image: library/mongo # base image off dockerhub
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=${DB_USER}"
      - "MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}"
  api: # node environment
    build:
      context: .
      dockerfile: ./scripts/Dockerfile.test
    image: pretzel_api_test # specifying name for built container
    command: [sh, -c, "cd /app && npm run test"]
    environment:
      - "API_HOST=${API_HOST}"
      - "API_PORT_EXT=${API_PORT_EXT}"
      - DB_HOST=database
      - "DB_PORT=27017"
      - "DB_NAME=${DB_NAME}"
      - "DB_USER=${DB_USER}"
      - "DB_PASS=${DB_PASS}"
      - "EMAIL_HOST=${EMAIL_HOST}"
      - "EMAIL_PORT=${EMAIL_PORT}"
      - "EMAIL_FROM=${EMAIL_FROM}"
      - "EMAIL_VERIFY=${EMAIL_VERIFY}"
      - "EMAIL_ADMIN=${EMAIL_ADMIN}"
    ports:
      # match ext / int ports for loopback
      - "${API_PORT_EXT}:${API_PORT_EXT}"
    volumes:
      # volume is mounted for development
      # will shift to embedded version for deployment
      - .:/app
    links:
     - database